### PR TITLE
jvm params

### PR DESCRIPTION
**Pull request by l3r8yJ**

### CODE REVIEW

**Comment by l3r8yJ** [comment]
@h1alexbel please turn on GH actions in the repo settings

**Comment by l3r8yJ** [comment]
@h1alexbel can you run it?

**Comment by h1alexbel** [comment]
@l3r8yJ no, we need setup docker workflow

**Comment by h1alexbel** [comment]
@l3r8yJ now it runs

**Comment by l3r8yJ** [comment]
@h1alexbel as you [can](https://github.com/eo-cqrs/eo-kafka-rultor-image/blob/master/.github/workflows/docker.yml) see, it's already set, or i miss something?

**Comment by l3r8yJ** [comment]
@h1alexbel i've checked it's okay
@rultor merge

**Comment by l3r8yJ** [comment]
@rultor merge

**Comment by l3r8yJ** [comment]
@rultor release, tag is `1.0.3`

**Pull request merged**
